### ISSUE TITLE
net.minecraft.util.ReportedException: Exception getting block type in world - Already decorating!!

### ISSUE THREAD

**Issue by syndicate25** [jss2a98aj/Et-Futurum#10]
Pastebin couldn't fit it all, but it hopefully is enough.  Seems to be a repeating pattern:

net.minecraft.world.gen.feature.WorldGenFlowers.func_76484_a(SourceFile:27)
[22:57:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at ganymedes01.etfuturum.world.EtFuturumWorldGenerator.generate(EtFuturumWorldGenerator.java:74)

Or something very similar.  This crash doesn't seem to have a rhyme or reason for happening.  I'm either just loading in to the world, moving around, or sitting completely still for a few minutes after loading in, and Minecraft just closes.

I've only tested this on superflat (though this was the "Overworld" preset, not the standard 3 block depth superflat world).  Happy to test on other modes if you'd like.  

This is also with my enormous list of mods and not a test in a fresh world with just the Et Futurum Requiem mod.  I can say however, that this was not an issue before I added this mod, when using the older version (most recent for 1.7.10) of Et Futurum.

This is all I was able to fit in the paste:  https://pastebin.com/Pimy0AKi

**Comment by syndicate25** [comment]
Side note on this one - seems it could be causing a memory leak as well.  The game crashing for "no reason" is because my RAM is hitting the 4gb cap.

**Comment by Roadhog360** [comment]
Known issue, was an error in the formatting of the decoration code, definitely a memory leak. I didn't want to push a whole new jar for this as it only affects superflats and thus isn't a huge deal, but this will be fixed in the next content update, soon.
