### ISSUE TITLE
Anvil/beacon/brewing stand/ Enchanting table get replaced even with config enableTileReplacement set to false

### ISSUE THREAD

**Issue by tyrael93** [jss2a98aj/Et-Futurum#16]
Just like it says on the tin.

**Comment by Roadhog360** [comment]
Oops, the event was linked to the Misc Sounds config option, not the Tile Replacement one...

**Comment by Roadhog360** [comment]
For now, you can manually override tiles you want to not be overridden, by turning off the beacon, enchantment, anvil etc options

**Comment by Roadhog360** [comment]
Fixed in upcoming release.
