### ISSUE TITLE
Crash on generating with Dragon Block C

### ISSUE THREAD

**Issue by DarianLStephens** [jss2a98aj/Et-Futurum#18]
I'm not sure why this is the case, but when I enable the new stones, the game crashes when attempting to create a world, citing flower-related worldgen issues.
Here's a log from having them enabled:
https://pastebin.com/S1nTQ9FV

Enabling or disabling flowers doesn't affect the fact that the game crashes, though it does seem to hang forever on world creation instead of outright crashing when they're disabled, but perhaps I just wasn't patient enough to wait for it.

**Comment by Roadhog360** [comment]
Do the new snapshots fix this? There were many bugs with worldgen in the previous builds including how flowers wouldn't disable.

**Comment by Roadhog360** [comment]
Release 2.1.0 forward should see this issue resolved.
