### ISSUE TITLE
Netherite Chestplate & Legging Defense Values

### ISSUE THREAD

**Issue by Lonemind** [jss2a98aj/Et-Futurum#24]
In vanilla Netherite Chestplates give 8 armor points and Netherite Leggings give 6.

As of 2.1.1 these two values are switched.

Not a bug worth a new patch, just one that can wait until you get some squashin' time.

**Comment by Roadhog360** [comment]
Are you sure 2.1.1 specifically changes this? I never touched these values in 2.1.1 or 2.1.0

**Comment by Roadhog360** [comment]
Looks like this was always there. Fix has been created and will be pushed in 2.1.2
