### ISSUE TITLE
Guardians and Elder Guardians?

### ISSUE THREAD

**Issue by MagmaBro123** [jss2a98aj/Et-Futurum#26]
Title.

**Comment by Roadhog360** [comment]
I'm going to be closing a majority of these as enitities blocks and items are among the most clear of my plans.

**Comment by MagmaBro123** [comment]
Not really sure why these are so hard.

**Comment by Roadhog360** [comment]
Guardians are among the hardest mobs to backport. I also didn't close this because it was hard or else more feature requests would be closed.

**Comment by MagmaBro123** [comment]
Ah...
