### ISSUE TITLE
Chisel compat. for Et's purpur blocks?

### ISSUE THREAD

**Issue by MagmaBro123** [jss2a98aj/Et-Futurum#30]
Title.

Chisel has purpur block variants, but Et's don't work when putting them in the Chisel's GUI. Surprisingly, Et's Copper works.

**Comment by Roadhog360** [comment]
Planned. The copper works because it's registered under the same oreDict names, but it's not actually registered properly.

**Comment by MagmaBro123** [comment]
Ah.
