### ISSUE TITLE
 Wither Skeletons [still] getting withered by wither roses.

### ISSUE THREAD

**Issue by tyrael93** [jss2a98aj/Et-Futurum#31]
My last issue #29 was closed after I posted proof of wither skeletons not getting hurt in vanilla 1.16.

I realized I couldn't open the issue again so I am opening a new one. I have no reason to see why this would be closed too.

In vanilla 1.16 wither skeletons do not get hurt by wither roses. I have tried this and tested this myself. Here is the proof.
![wither1](https://user-images.githubusercontent.com/5557920/114303684-ac9fe580-9acf-11eb-85ae-cc20b209f08d.png)
![wither 2](https://user-images.githubusercontent.com/5557920/114303685-ad387c00-9acf-11eb-8430-c9424f6011a7.png)

You don't have to take my word for it, I've also found additional proof that they don't, in the form of several videos with millions of views, which I will post here as a gesture of good will.

https://www.youtube.com/watch?v=HJYqVwmAbxY
https://www.youtube.com/watch?v=le_tTlKEbyw

These videos are from minecraft 1.16.

This issue was previously closed because 
![Screenshot from 2021-04-11 14-11-37](https://user-images.githubusercontent.com/5557920/114303723-db1dc080-9acf-11eb-814f-1a2cb8b639e0.png)

I ask you to please don't close this issue again, because it is clearly not "working as intended", if "as intended" is meant to be "as vanilla works".

I know that in 1.7 Wither Skeletons and regular Skeletons are the same entity and that the split only happened later on, but ever since the addition of wither roses, wither skeletons got a wither immunity and can pass through wither roses unharmed and even spawn on them. This also lets you create quite easy wither skeleton farms just by placing large amounts of wither roses.

Please see the closed issue for a suggestion on how to handle it. Mostly, I'm opening this again to have an answer about why it was closed.

**Comment by Roadhog360** [comment]
Please do not duplicate issues, wait for them to be reopened.
