### ISSUE TITLE
Backport the Spectator gamemode?

### ISSUE THREAD

**Issue by MagmaBro123** [jss2a98aj/Et-Futurum#32]

**Comment by Roadhog360** [comment]
This may not be in base Et Futurum due to likely requiring base class edits.

**Comment by MagmaBro123** [comment]
Ah.

Well, any mods that do this? Cause this would be cool to have.

**Comment by Roadhog360** [comment]
An upcoming coremod I am working on may have it.

**Comment by MagmaBro123** [comment]
Ah, cool.
