### ISSUE TITLE
Mood for Caves and Nether

### ISSUE THREAD

**Issue by DelirusCrux** [jss2a98aj/Et-Futurum#5]
Right now the Code for Moods is in the ServerEventHandler, together with code that is for biome music.

I would put that in a different class and Register that in the ClientProxy instead, since it "could" cause issues if client side code is registered server side

**Comment by Roadhog360** [comment]
Is there no possibility that a sound could be triggered serverside and not be overridden because all the code was moved to the client? That's why the sound code is where it is now, I felt some sounds may be sent by the server and not overridden.

**Comment by Roadhog360** [comment]
Closed: Neaely 2 weeks with no response
