### ISSUE TITLE
Netherlicious Nether Ambience Compability

### ISSUE THREAD

**Issue by DelirusCrux** [jss2a98aj/Et-Futurum#6]
To make sure you don't override custom Nether Ambience when Netherlicious is installed
you can check if Netherlicious already has Nether Ambience enabled.

This should allow you to read the config of netherlicious and get the specific value. I'd suggest not registering your Nether Ambience if the following is true when netherlicious is loaded.

This code has to be in the Main Mod File in:
	@EventHandler
	public void preinit(FMLPreInitializationEvent event) 

		public static boolean NetherAmbienceNetherlicious;
		
		Configuration Netherlicious;
		{
			if (Loader.isModLoaded("netherlicious")) {
				Netherlicious = new Configuration(
						new File(event.getModConfigurationDirectory() + "/netherlicious/Biome_Sound_Configuration.cfg"));
				NetherAmbienceNetherlicious = Netherlicious.get("1 nether ambience", "Allow Biome specific sounds to play", true).getBoolean();

			}
		}

**Comment by DelirusCrux** [comment]
Turns out EtFuturum does not override ambience in Nether Biomes with netherlicious, but adds it's own ambience on top

**Comment by tyrael93** [comment]
@Roadhog360 
Just a heads up, now that netherlicious' config folder has been renamed Netherlicious (with a capital N), the mod creates a second netherlicious folder with an empty text file named Biome_Sound_Configuration.cfg.
![netherlic](https://user-images.githubusercontent.com/5557920/141811539-57c53e01-b7cc-4db5-8130-1f57068a316a.png)

**Comment by GregoriusT** [comment]
Please note, the second folder only appears for people that are smart enough to not use Windows. ;)

**Comment by DelirusCrux** [comment]
Hi, I'm the author of netherlicious, I didn't do anythingt to the configs lately besides adding new options to the Entity_Configuration yesterday. I have no idea what is happening there, but I did not rename the Config Folder

**Comment by tyrael93** [comment]
> Hi, I'm the author of netherlicious, I didn't do anythingt to the configs lately besides adding new options to the Entity_Configuration yesterday. I have no idea what is happening there, but I did not rename the Config Folder

oh hey crux
That might just be a linux quirk related to , as I think greg was hinting at
What about the second part of the issue related to netherlicious biome music overriding etfuturum's same music ambience? I'm having trouble finding a way to trigger biome music to play on cue to test it properly, if that's even possible.

**Comment by DelirusCrux** [comment]
The thing is, if that config option is set to false I'm not registering the music system, so I can't override etfuturums music if it is set to false. Just checked again, it's only registered if the option is true

**Comment by DelirusCrux** [comment]
But yeah, maybe @Roadhog360 need to change the "N" to uppercase in the function I wrote to check my config. Maybe that's what's causing it

**Comment by makamys** [comment]
The Netherlicious config folder has always been capitalized in all my instances (going back to 2021-02-12) , so this issue has been around for a while.

> I'm having trouble finding a way to trigger biome music to play on cue to test it properly, if that's even possible.

You can use the command `/playsound <sound name> @p`

**Comment by GregoriusT** [comment]
I did fix the lowercase "n", so it should work fine now? Unsure if this was enough to fix the Issue though.

**Comment by tyrael93** [comment]
I'll give it a whirl then, thanks guys

**Comment by makamys** [comment]
`./gradlew build` on a freshly cloned repo works for me 🤷

**Comment by tyrael93** [comment]
you have to understand, I'm a special needs child
it's most likely something asinine, but my knowledge of these things is basically zero so everything that happens is a huge :stop_sign:
![Screenshot from 2021-11-16 19-20-20](https://user-images.githubusercontent.com/5557920/142043150-3132acbc-6410-406e-b1d4-5c2ca2d5ad40.png)

**Comment by GregoriusT** [comment]
./gradlew --refresh-dependencies setupDecompWorkspace build

As for java, uhh do you have java 8 installed in some way? (i cant even explain how to do that one because oracle decided to nuke the java 8 PPAs for Linux..., and I'm not a Windows User anymore since years)

**Comment by DelirusCrux** [comment]
@makamys yeah Netherlicious always had a capital N in the config folder, but when I wrote that function to read my config file I didn't think about if it could matter. On windows it worked fine, so there it doesn't seem to matter.

**Comment by Roadhog360** [comment]
> @makamys yeah Netherlicious always had a capital N in the config folder, but when I wrote that function to read my config file I didn't think about if it could matter. On windows it worked fine, so there it doesn't seem to matter.

It always matters when it comes to system functionality. Other OSs are case-sensitive and you never know the edge cases.

**Comment by Roadhog360** [comment]
> ./gradlew --refresh-dependencies setupDecompWorkspace build
> 
> As for java, uhh do you have java 8 installed in some way? (i cant even explain how to do that one because oracle decided to nuke the java 8 PPAs for Linux..., and I'm not a Windows User anymore since years)

You can use OpenJDK.
